use_frameworks!

platform :ios, '10.3'

target 'HLFUITextExtensions_Example' do
  pod 'HLFUITextExtensions', :path => '../'

  target 'HLFUITextExtensions_Tests' do
    inherit! :search_paths
  end
end
